services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: report-scribe-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - report-scribe-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: report-scribe-backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - report-scribe-network

networks:
  report-scribe-network:
    driver: bridge